# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: imranismail
    name: cloudcreds
  prerelease: auto
dockers:
- image_templates:
  - "imranismail/cloudcreds:latest"
  - "imranismail/cloudcreds:{{ .Tag }}"
  - "imranismail/cloudcreds:v{{ .Major }}"