// Code generated by qtc from "message.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line message.qtpl:1
package templates

//line message.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line message.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line message.qtpl:2
type Message struct {
	Content string
	Context string
	Color   string
}

//line message.qtpl:8
func (msg *Message) StreamRender(qw422016 *qt422016.Writer) {
//line message.qtpl:8
	qw422016.N().S(`
<html>
  <head>
    <title>Cloudcreds | `)
//line message.qtpl:11
	qw422016.E().S(msg.Context)
//line message.qtpl:11
	qw422016.N().S(`</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body class="bg-gray-200">
    <main class="flex justify-center">
      <div class="text-center mt-12">
        <div class="p-2 bg-`)
//line message.qtpl:17
	qw422016.E().S(msg.Color)
//line message.qtpl:17
	qw422016.N().S(`-800 items-center text-`)
//line message.qtpl:17
	qw422016.E().S(msg.Color)
//line message.qtpl:17
	qw422016.N().S(`-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
          <span class="flex rounded-full bg-`)
//line message.qtpl:18
	qw422016.E().S(msg.Color)
//line message.qtpl:18
	qw422016.N().S(`-500 uppercase px-2 py-1 text-xs font-bold mr-3">`)
//line message.qtpl:18
	qw422016.E().S(msg.Context)
//line message.qtpl:18
	qw422016.N().S(`</span>
          <span class="font-semibold mr-2 text-left flex-auto">`)
//line message.qtpl:19
	qw422016.E().S(msg.Content)
//line message.qtpl:19
	qw422016.N().S(`</span>
        </div>
      </div>
    </main>
  </body>
</html>
`)
//line message.qtpl:25
}

//line message.qtpl:25
func (msg *Message) WriteRender(qq422016 qtio422016.Writer) {
//line message.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line message.qtpl:25
	msg.StreamRender(qw422016)
//line message.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line message.qtpl:25
}

//line message.qtpl:25
func (msg *Message) Render() string {
//line message.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line message.qtpl:25
	msg.WriteRender(qb422016)
//line message.qtpl:25
	qs422016 := string(qb422016.B)
//line message.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line message.qtpl:25
	return qs422016
//line message.qtpl:25
}
