// Code generated by qtc from "new_session.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line new_session.qtpl:1
package templates

//line new_session.qtpl:1
import "github.com/aws/aws-sdk-go/aws/arn"

//line new_session.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line new_session.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line new_session.qtpl:3
type RolesByAccount map[string][]arn.ARN

func (rba *RolesByAccount) Has(arnString string) bool {
	for _, arns := range *rba {
		for _, arn := range arns {
			if arn.String() == arnString {
				return true
			}
		}
	}

	return false
}

//line new_session.qtpl:17
func StreamNewSession(qw422016 *qt422016.Writer, rba *RolesByAccount, state string) {
//line new_session.qtpl:17
	qw422016.N().S(`
<html>
  <head>
    <title>Cloud Credentials | Sign In</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body class="bg-gray-200">
    <main class="flex justify-center">
      <form method="post" action="/session" class="bg-white shadow-md rounded px-8 pt-6 pb-8 m-0 mt-24">
        <span class="font-extrabold text-gray-700 text-center block mb-6 text-xl">Amazon Web Service</span>
        <input type="hidden" name="state" value="`)
//line new_session.qtpl:27
	qw422016.E().S(state)
//line new_session.qtpl:27
	qw422016.N().S(`">
        <div class="mb-4">
          <span class="font-normal text-gray-500 text-sm w-full">Select IAM Role</span>
          <div class="inline-block relative w-full">
            <select name="role" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
              `)
//line new_session.qtpl:32
	for account, roles := range *rba {
//line new_session.qtpl:32
		qw422016.N().S(`
                <optgroup label="`)
//line new_session.qtpl:33
		qw422016.E().S(account)
//line new_session.qtpl:33
		qw422016.N().S(`">
                  `)
//line new_session.qtpl:34
		for _, role := range roles {
//line new_session.qtpl:34
			qw422016.N().S(`
                    <option value="`)
//line new_session.qtpl:35
			qw422016.N().S(role.String())
//line new_session.qtpl:35
			qw422016.N().S(`">`)
//line new_session.qtpl:35
			qw422016.E().S(role.Resource)
//line new_session.qtpl:35
			qw422016.N().S(`</option>
                  `)
//line new_session.qtpl:36
		}
//line new_session.qtpl:36
		qw422016.N().S(`
                </optgroup>
              `)
//line new_session.qtpl:38
	}
//line new_session.qtpl:38
	qw422016.N().S(`
            </select>
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
              <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
            </div>
          </div>
        </div>
        <button class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
          Sign In
        </button>
      </form>
    </main>
  </body>
</html>
`)
//line new_session.qtpl:52
}

//line new_session.qtpl:52
func WriteNewSession(qq422016 qtio422016.Writer, rba *RolesByAccount, state string) {
//line new_session.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line new_session.qtpl:52
	StreamNewSession(qw422016, rba, state)
//line new_session.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line new_session.qtpl:52
}

//line new_session.qtpl:52
func NewSession(rba *RolesByAccount, state string) string {
//line new_session.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line new_session.qtpl:52
	WriteNewSession(qb422016, rba, state)
//line new_session.qtpl:52
	qs422016 := string(qb422016.B)
//line new_session.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line new_session.qtpl:52
	return qs422016
//line new_session.qtpl:52
}
